#' @title Create geographical heatmaps from dispersion field list
#'
#' @description Creates geographical heatmaps depicting global dispersion field
#' patterns of the different sites in the local data frame from the dispersion
#' field list generated by the \code{CreateGlobalAbundanceFields} and a global
#' shapefile to sketch the background.
#'
#' @param dispersion.field The list of dispersion field matrices per site generated
#'                         by \code{CreateGlobalAbundanceFields} function.
#' @param global_shapefile Global shapefile to read shape lines for background.
#'
#' @examples
#' dispersion.field <- get(load("dispersion_field_mat.rda"))
#' global_shapefile <- readShapeLines('ne_50m_admin_0_countries.shp', proj4string=proj)
#' maps <- CreateMapsFromDispersionFields(dispersion.field, global_shapefile )
#'
#' @importFrom rasterVis rasterTheme
#' @import grDevices
#' @importFrom readShapeLines maptools
#' @export

##########  Create a set of maps from dispersion field data ##################

CreateMapsFromDispersionFields <- function(dispersion.field,
                                           global_shapefile)
{
  newtheme <- rasterVis::rasterTheme(region = grDevices::colorRampPalette(c("darkseagreen3","orange","red"))( 100 ))
#  GlobalAdm <- readShapeLines('ne_50m_admin_0_countries.shp', proj4string=proj)
  ADF <- list()
  for (l in 1:length(dispersion.field)){
    ADF[[i]] <- levelplot(dispersion.field[[l]],
                          par.settings=newtheme,
                          contour=F,margin=FALSE,
                          colorkey=list(at=seq(0, 50, 1),
                                        labels=list(at=c(12.5, 25,37.5,50),
                                                    labels=c("25%", "50%", "75%", "100%")))) +
      layer({
        sp.lines(global_shapefile, col='black', lwd=0.5)
      })
  }
  names(ADF)<-names(dispersion.field)
  return(ADF)
}
