#' @title Create geographical heatmaps from dispersion field list
#'
#' @description Creates geographical heatmaps depicting global dispersion field
#' patterns of the different sites in the local data frame from the dispersion
#' field list generated by the \code{dispersion_fields_create} and a global
#' shapefile to sketch the background.
#'
#' @param dispersion.field The list of dispersion field matrices per site 
#'                         generated by \code{dispersion_fields_create} function.
#' @param global_shapefile Global shapefile to read shape lines for country 
#'                         boundaries in background.
#' @param raster_latlim The latitudinal range of the dispersion fields
#' @param raster_longlim the longitudinal range of the dispersion fields
#' @param proj the CRS projection of the global shapfile to apply to each 
#'             dispersion field matrix
#' @param color_ramp Color palette to be for the heat map
#'
#' @examples
#' data("dispersion_field_ex")
#' proj <- CRS(' +proj=longlat +ellps=WGS84')
#' global_shapefile <- sf::st_read(system.file("extdata",
#'                     "ne_110m_coastline",
#'                     "ne_110m_coastline.shp",
#'                      package = "ecostructure"), 
#'                     quiet = TRUE)
#' maps <- dispersion_fields_to_maps(dispersion_field_ex, global_shapefile )
#'
#' @importFrom raster raster
#' @importFrom rasterVis rasterTheme levelplot
#' @importFrom sp sp.lines
#' @importFrom latticeExtra layer
#' @import grDevices
#' @export

##########  Create a set of maps from dispersion field data ##################

dispersion_fields_plot <- function(dispersion.field,
                                   input = "matrix",
                                   raster_latlim = c(50,70),
                                   raster_longlim = c(50,70),
                                   proj=CRS(' +proj=longlat +ellps=WGS84'),
                                   color_ramp = c("darkseagreen3","orange","red"))
{
  global_boundaries <- sf::st_read('ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp', quiet=T)
  global_coast <- sf::st_read('ne_110m_coastline/ne_110m_coastline.shp', quiet=T)
  
  newtheme <- rasterVis::rasterTheme(region = grDevices::colorRampPalette(color_ramp)( 100 ))
  
  if(input=="matrix"){
    xmin<-raster_longlim[1]
    xmax<-raster_longlim[2]
    ymin<-raster_latlim[1]
    ymax<-raster_latlim[2]
    ADF <- list()
    for (i in 1:length(dispersion.field)){
      r <- raster::raster(dispersion.field[[i]],
                          xmn=xmin,
                          xmx=xmax,
                          ymn=ymin,
                          ymx=ymax,
                          crs=proj)
      ADF[[i]] <- rasterVis::levelplot(r,
                            par.settings=newtheme,
                            contour=F,margin=FALSE,
                            at=seq(1, summary(r)[5], length.out=100),
                            colorkey=list(at=seq(0, 100, 1),
                                   labels=list(at=c(25,50,75,100),
                                   labels=c("25%", "50%", "75%", "100%")))) +
        latticeExtra::layer(sp::sp.lines(as(global_boundaries, 'Spatial'),
                                         col='black', lwd=0.5)) +
        latticeExtra::layer(sp::sp.lines(as(global_coast, 'Spatial'),
                                         col='black', lwd=0.5))
    }
  } else if (input=="raster"){
    ADF <- list()
    for (i in 1:length(dispersion.field)){
      ADF[[i]] <- rasterVis::levelplot(dispersion.field[[i]],
                            par.settings=newtheme,
                            contour=F,margin=FALSE,
                            at=seq(1, summary(dispersion.field[[i]])[5], 
                                   length.out=100),
                            colorkey=list(at=seq(0, 100, 1),
                                     labels=list(at=c(25,50,75,100),
                                     labels=c("25%", "50%", "75%", "100%")))) +
        latticeExtra::layer(sp.lines(as(global_boundaries, 'Spatial'),
                                     col='black', lwd=0.5)) +
        latticeExtra::layer(sp.lines(as(global_coast, 'Spatial'),
                                     col='black', lwd=0.5))
    }
  }
  names(ADF)<-names(dispersion.field)
  return(ADF)
}
